namespace: "cyberark"
name: "conjur"
version: "1.0.5"
readme: README.md
authors:
    - CyberArk Business Development (@cyberark-bizdev)
    - Edward Nunez (@enunez-cyberark)
    - James Stutes (@JimmyJamCABD)
    - Srdjan Grubor (@sgnn7)
description: "This is a Collection of CyberArk Conjur/DAP toolkit."
license: "Apache-2.0"
tags:
  - cyberark
  - conjur
  - access
  - security
  - account
  - vault
  - identity
  - credential
  - secret
  - privileged
  - devops
repository: "https://github.com/cyberark/ansible-conjur-collection"
